name: Add POC Tag on PR to Integration

on:
  pull_request:
    branches:
      - integracion

jobs:
  add_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set tag name
        run: echo "TAG_NAME=POC" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Verifica si el tag ya existe y lo elimina antes de crear el nuevo
          if git rev-parse $TAG_NAME >/dev/null 2>&1; then
            git tag -d $TAG_NAME
            git push origin :refs/tags/$TAG_NAME
          fi

          # Crea y empuja el nuevo tag
          git tag $TAG_NAME
          git push origin $TAG_NAME